name: app
description: "Aplicativo do Instituto Vida para Todos."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluttericon: ^2.0.0
  cupertino_icons: ^1.0.8
  i18n_extension: ^15.0.4

  convex_bottom_bar: ^3.2.0
  easy_splash_screen: ^1.0.4
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  lint_staged: ^0.5.1
  husky: ^0.1.7
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.14.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/banners/
    - assets/icons/

# configure lint_staged
lint_staged:
  'lib/**.dart': dart format -l 120 && dart analyze --fatal-infos --fatal-warnings && dart fix --apply

# https://pub.dev/packages/flutter_launcher_icons
# must run `flutter pub run flutter_launcher_icons` after updating icon in order to take effect
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

